SURVEY_QUESTIONS = [
    {
        "step": 1,
        "id": "home_type",
        "type": "select",
        "label": "What type of home do you live in?",
        "options": [
            {"value": "apartment", "label": "Apartment / Flat"},
            {"value": "house", "label": "Detached House"},
            {"value": "townhouse", "label": "Townhouse / Terrace"},
            {"value": "studio", "label": "Studio"},
        ],
        "required": True,
    },
    {
        "step": 1,
        "id": "occupants",
        "type": "number",
        "label": "How many people live in your home?",
        "min": 1,
        "max": 20,
        "required": True,
    },
    {
        "step": 1,
        "id": "bedrooms",
        "type": "number",
        "label": "How many bedrooms?",
        "min": 1,
        "max": 10,
        "required": True,
    },
    {
        "step": 2,
        "id": "heating_type",
        "type": "select",
        "label": "What is your main heating type?",
        "options": [
            {"value": "electric", "label": "Electric Heating"},
            {"value": "gas", "label": "Gas Heating"},
            {"value": "heat_pump", "label": "Heat Pump"},
            {"value": "solar", "label": "Solar / Renewable"},
        ],
        "required": True,
    },
    {
        "step": 2,
        "id": "appliances",
        "type": "multiselect",
        "label": "Which of these appliances do you use regularly?",
        "options": [
            {"value": "washer", "label": "Washing Machine"},
            {"value": "dryer", "label": "Clothes Dryer"},
            {"value": "dishwasher", "label": "Dishwasher"},
            {"value": "oven", "label": "Oven / Stove"},
            {"value": "ac", "label": "Air Conditioning"},
            {"value": "pool_pump", "label": "Pool Pump"},
            {"value": "ev_charger", "label": "EV Charger"},
        ],
        "required": False,
    },
    {
        "step": 2,
        "id": "has_tou",
        "type": "select",
        "label": "Do you have a time-of-use electricity plan?",
        "options": [
            {"value": "yes", "label": "Yes"},
            {"value": "no", "label": "No"},
            {"value": "unsure", "label": "I'm not sure"},
        ],
        "required": True,
    },
    {
        "step": 3,
        "id": "daily_budget_kwh",
        "type": "number",
        "label": "What is your daily energy budget (kWh)?",
        "min": 1,
        "max": 100,
        "required": True,
    },
    {
        "step": 3,
        "id": "electricity_rate_cents",
        "type": "number",
        "label": "What is your electricity rate (cents per kWh)?",
        "min": 1,
        "max": 100,
        "required": True,
    },
    {
        "step": 3,
        "id": "goal",
        "type": "select",
        "label": "What is your main energy goal?",
        "options": [
            {"value": "save_money", "label": "Save money on bills"},
            {"value": "reduce_usage", "label": "Reduce overall usage"},
            {"value": "solar_optimise", "label": "Optimise solar usage"},
            {"value": "monitor", "label": "Just monitor usage"},
        ],
        "required": True,
    },
]
